### PR TITLE
Add new environment variables to push to gcs

### PR DESCRIPTION
**Pull request by rodriguezcondec**

### CODE REVIEW

**Review by kylegranger — APPROVED** [review]
👍

**Review by aphelionz — APPROVED** [review]

**Review by Rqnsom — APPROVED** [review]

**Review by zeapoz — CHANGES_REQUESTED** [review]
Changes are looking good to me, but these lines will also need to be changed (in each workflow).
https://github.com/runziggurat/zcash/blob/a5519364f595b8e637ae45bac239168fea0247e5/.github/workflows/zcashd-nightly.yml#L52-L63

**Comment by zeapoz** [comment]
You can probably just remove the uploading of the previous results and instead directly fetch `latest.$FILENAME` here https://github.com/runziggurat/ziggurat-core/blob/1de5c466c4e0216506aaf2b76b291c684f439aaf/.github/workflows/diff-with-previous.yml#L11-L13

**Comment by rodriguezcondec** [comment]
> Changes are looking good to me, but these lines will also need to be changed (in each workflow).
> 
> https://github.com/runziggurat/zcash/blob/a5519364f595b8e637ae45bac239168fea0247e5/.github/workflows/zcashd-nightly.yml#L52-L63

I can take a look but I don't think this would break now the CI right? It would just create a `results/` folder within the github actions virtual machine instance to run `./ziggurat_test` and then upload these results, 🤔 so in theory, we could leave it as it is and it should work right? @zeapoz

**Comment by rodriguezcondec** [comment]
> then fail since there no

Yeah, you're right, will open a PR to change that. I can directly remove that step and that would be it? Or do i need to include https://github.com/runziggurat/ziggurat-core/blob/1de5c466c4e0216506aaf2b76b291c684f439aaf/.github/workflows/diff-with-previous.yml#L11-L13 as well?

**Pull request merged**
